export const DEFAULT_WINDOWS_MCP_HOST = '127.0.0.1'
export const DEFAULT_WINDOWS_MCP_PORT = 8010
export const DEFAULT_WINDOWS_MCP_ENDPOINT = `http://${DEFAULT_WINDOWS_MCP_HOST}:${String(DEFAULT_WINDOWS_MCP_PORT)}/mcp`
